import type { Liga } from "../entidades/modelos";
export const LIGAS_SUPORTADAS: Liga[] = [
  {
    id: "brasileirao",
    idExterno: 71,
    nome: "Brasileirão Série A",
    pais: "Brasil",
    bandeira: "BR",
    reputacao: 78,
    forcaMedia: 73,
    quantidadeClubes: 20,
  },
  {
    id: "premier-league",
    idExterno: 39,
    nome: "Premier League",
    pais: "Inglaterra",
    bandeira: "GB",
    reputacao: 98,
    forcaMedia: 81,
    quantidadeClubes: 20,
  },
  {
    id: "la-liga",
    idExterno: 140,
    nome: "La Liga",
    pais: "Espanha",
    bandeira: "ES",
    reputacao: 93,
    forcaMedia: 78,
    quantidadeClubes: 20,
  },
  {
    id: "serie-a",
    idExterno: 135,
    nome: "Serie A",
    pais: "Itália",
    bandeira: "IT",
    reputacao: 90,
    forcaMedia: 77,
    quantidadeClubes: 20,
  },
  {
    id: "bundesliga",
    idExterno: 78,
    nome: "Bundesliga",
    pais: "Alemanha",
    bandeira: "DE",
    reputacao: 90,
    forcaMedia: 77,
    quantidadeClubes: 18,
  },
  {
    id: "ligue-1",
    idExterno: 61,
    nome: "Ligue 1",
    pais: "França",
    bandeira: "FR",
    reputacao: 85,
    forcaMedia: 74,
    quantidadeClubes: 18,
  },
].map((liga) => ({
  ...liga,
  regras: { pontosVitoria: 3, pontosEmpate: 1, amarelosSuspensao: 3 },
}));
