import type { Liga } from "../entidades/modelos";

export const TEMPORADA_TRANSFERMARKT = "2026";

export const LIGAS_SUPORTADAS: Liga[] = [
  {
    id: "brasileirao",
    idTransfermarkt: "BRA1",
    termoBusca: "Brasileirão",
    nome: "Brasileirão Série A",
    pais: "Brasil",
    bandeira: "BR",
    divisao: 1,
    reputacao: 78,
    forcaMedia: 73,
    quantidadeClubes: 20,
  },
  {
    id: "brasileirao-b",
    idTransfermarkt: "BRA2",
    termoBusca: "Série B",
    nome: "Brasileirão Série B",
    pais: "Brasil",
    bandeira: "BR",
    divisao: 2,
    reputacao: 62,
    forcaMedia: 64,
    quantidadeClubes: 20,
  },
  {
    id: "premier-league",
    idTransfermarkt: "GB1",
    termoBusca: "Premier League",
    nome: "Premier League",
    pais: "Inglaterra",
    bandeira: "GB",
    divisao: 1,
    reputacao: 98,
    forcaMedia: 81,
    quantidadeClubes: 20,
  },
  {
    id: "championship",
    idTransfermarkt: "GB2",
    termoBusca: "Championship",
    nome: "Championship",
    pais: "Inglaterra",
    bandeira: "GB",
    divisao: 2,
    reputacao: 75,
    forcaMedia: 70,
    quantidadeClubes: 24,
  },
  {
    id: "la-liga",
    idTransfermarkt: "ES1",
    termoBusca: "LaLiga",
    nome: "La Liga",
    pais: "Espanha",
    bandeira: "ES",
    divisao: 1,
    reputacao: 93,
    forcaMedia: 78,
    quantidadeClubes: 20,
  },
  {
    id: "la-liga-2",
    idTransfermarkt: "ES2",
    termoBusca: "LaLiga 2",
    nome: "LaLiga 2",
    pais: "Espanha",
    bandeira: "ES",
    divisao: 2,
    reputacao: 68,
    forcaMedia: 66,
    quantidadeClubes: 22,
  },
  {
    id: "serie-a",
    idTransfermarkt: "IT1",
    termoBusca: "Serie A",
    nome: "Serie A",
    pais: "Itália",
    bandeira: "IT",
    divisao: 1,
    reputacao: 90,
    forcaMedia: 77,
    quantidadeClubes: 20,
  },
  {
    id: "serie-b",
    idTransfermarkt: "IT2",
    termoBusca: "Serie B",
    nome: "Serie B",
    pais: "Itália",
    bandeira: "IT",
    divisao: 2,
    reputacao: 67,
    forcaMedia: 65,
    quantidadeClubes: 20,
  },
  {
    id: "bundesliga",
    idTransfermarkt: "L1",
    termoBusca: "Bundesliga",
    nome: "Bundesliga",
    pais: "Alemanha",
    bandeira: "DE",
    divisao: 1,
    reputacao: 90,
    forcaMedia: 77,
    quantidadeClubes: 18,
  },
  {
    id: "bundesliga-2",
    idTransfermarkt: "L2",
    termoBusca: "2. Bundesliga",
    nome: "2. Bundesliga",
    pais: "Alemanha",
    bandeira: "DE",
    divisao: 2,
    reputacao: 70,
    forcaMedia: 67,
    quantidadeClubes: 18,
  },
  {
    id: "ligue-1",
    idTransfermarkt: "FR1",
    termoBusca: "Ligue 1",
    nome: "Ligue 1",
    pais: "França",
    bandeira: "FR",
    divisao: 1,
    reputacao: 85,
    forcaMedia: 74,
    quantidadeClubes: 18,
  },
  {
    id: "ligue-2",
    idTransfermarkt: "FR2",
    termoBusca: "Ligue 2",
    nome: "Ligue 2",
    pais: "França",
    bandeira: "FR",
    divisao: 2,
    reputacao: 63,
    forcaMedia: 62,
    quantidadeClubes: 18,
  },
].map((liga) => ({
  ...liga,
  regras: { pontosVitoria: 3, pontosEmpate: 1, amarelosSuspensao: 3 },
})) as Liga[];
